export const UNIVERSITIES = [
  'Australian Catholic University (ACU)',
  'Bond University',
  'Charles Darwin University',
  'Charles Sturt University',
  'CQUniversity',
  'Curtin University',
  'Deakin University',
  'Edith Cowan University',
  'Federation University',
  'Flinders University',
  'Griffith University',
  'James Cook University',
  'La Trobe University',
  'Macquarie University',
  'Monash University',
  'Murdoch University',
  'Queensland University of Technology (QUT)',
  'RMIT University',
  'Southern Cross University',
  'Swinburne University of Technology',
  'University of Adelaide',
  'University of Canberra',
  'University of Melbourne',
  'University of New England',
  'University of New South Wales (UNSW)',
  'University of Newcastle',
  'University of Queensland',
  'University of South Australia',
  'University of Southern Queensland',
  'University of Sydney',
  'University of Tasmania',
  'University of Technology Sydney (UTS)',
  'University of the Sunshine Coast',
  'University of Western Australia',
  'University of Wollongong',
  'Victoria University',
  'Western Sydney University',
].sort((a, b) => a.localeCompare(b));
